### ISSUE TITLE
Qt5Widgets版本依赖问题

### ISSUE THREAD

**Issue by yxpandjay** [qiushao/kkshell#1]
用
sudo apt install build-essential cmake qt5-default qtcreator
sudo apt install qt5-doc qt5-doc-html qtbase5-doc-html qtbase5-examples
sudo apt install libqt5serialport5-dev qt5serialport-examples
sudo apt install libutf8proc-dev lxqt-build-tools
sudo apt install libssh2-1-dev
sudo apt install libssl-dev
这些指令装的qt5

编译时:
CMake Error at thirdparty/qtermwidget/CMakeLists.txt:39 (find_package):
  Could not find a configuration file for package "Qt5Widgets" that is
  compatible with requested version "5.10.0".

  The following configuration files were considered but not accepted:

    /home/modian/anaconda3/lib/cmake/Qt5Widgets/Qt5WidgetsConfig.cmake, version: 5.9.7
    /usr/lib/x86_64-linux-gnu/cmake/Qt5Widgets/Qt5WidgetsConfig.cmake, version: 5.9.5

**Comment by yxpandjay** [comment]
依赖版本号改低后，编译报错
Determining if the pthread_create exist failed with the following output:
Change Dir: /home/modian/workspace/Time/2020.11/kkshell/kkshell/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_bdd68/fast"
/usr/bin/make -f CMakeFiles/cmTC_bdd68.dir/build.make CMakeFiles/cmTC_bdd68.dir/build
make[1]: Entering directory '/home/modian/workspace/Time/2020.11/kkshell/kkshell/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_bdd68.dir/CheckSymbolExists.c.o
/usr/bin/cc    -o CMakeFiles/cmTC_bdd68.dir/CheckSymbolExists.c.o   -c /home/modian/workspace/Time/2020.11/kkshell/kkshell/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_bdd68
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_bdd68.dir/link.txt --verbose=1
/usr/bin/cc      -rdynamic CMakeFiles/cmTC_bdd68.dir/CheckSymbolExists.c.o  -o cmTC_bdd68 
CMakeFiles/cmTC_bdd68.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0x1b): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_bdd68.dir/build.make:97: recipe for target 'cmTC_bdd68' failed
make[1]: *** [cmTC_bdd68] Error 1
make[1]: Leaving directory '/home/modian/workspace/Time/2020.11/kkshell/kkshell/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_bdd68/fast' failed
make: *** [cmTC_bdd68/fast] Error 2

File /home/modian/workspace/Time/2020.11/kkshell/kkshell/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/modian/workspace/Time/2020.11/kkshell/kkshell/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_dc93b/fast"
/usr/bin/make -f CMakeFiles/cmTC_dc93b.dir/build.make CMakeFiles/cmTC_dc93b.dir/build
make[1]: Entering directory '/home/modian/workspace/Time/2020.11/kkshell/kkshell/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_dc93b.dir/CheckFunctionExists.c.o
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_dc93b.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.10/Modules/CheckFunctionExists.c
Linking C executable cmTC_dc93b
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_dc93b.dir/link.txt --verbose=1
/usr/bin/cc  -DCHECK_FUNCTION_EXISTS=pthread_create    -rdynamic CMakeFiles/cmTC_dc93b.dir/CheckFunctionExists.c.o  -o cmTC_dc93b -lpthreads 
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_dc93b.dir/build.make:97: recipe for target 'cmTC_dc93b' failed
make[1]: *** [cmTC_dc93b] Error 1
make[1]: Leaving directory '/home/modian/workspace/Time/2020.11/kkshell/kkshell/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_dc93b/fast' failed
make: *** [cmTC_dc93b/fast] Error 2

**Comment by qiushao** [comment]
你是什么版本的系统？ @yxpandjay 
我这边是用 linux mint 20 测试过而已，其他系统还没试过

**Comment by qiushao** [comment]
从上面的编译错误来看是链接 pthreads 的时候出现错误了。
目前其实是不需要依赖 pthreads 的，我已经把 pthreads 和 libssh2 的依赖给去掉了。
更新一下代码试试看 @yxpandjay

**Comment by yxpandjay** [comment]
你好，我的ubuntu版本是 18.04.5 LTS

**Comment by yxpandjay** [comment]
![image](https://user-images.githubusercontent.com/31854414/100424922-43dc4180-30c9-11eb-86fc-e8d1fcc8b1b1.png)
最新版本编译的结果

**Comment by yxpandjay** [comment]
-- Detecting C compile features - done
CMake Error at thirdparty/qtermwidget/CMakeLists.txt:47 (include):
  include could not find load file:

    LXQtPreventInSourceBuilds


-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Success

**Comment by qiushao** [comment]
特意安装了个 ubuntu 18.04 虚拟机来编译测试。
最新代码已经可以在 ubuntu 18.04 上编译运行了。
@yxpandjay 再更新代码试试

**Comment by yxpandjay** [comment]
没问题啦。正常编译，运行~~
感谢！
